version: '2.4'
services:

  jvm:
    image: hello-world
    build:
      context: .
      dockerfile: Dockerfile-jvm
    ports:
      - "127.0.0.1:9001:8080"

  graalvm:
    image: hello-world
    build:
      context: .
      dockerfile: Dockerfile-graalvm
    volumes:
      - ./target/native-image:/tmp/native-image
    ports:
      - "127.0.0.1:9002:8080"

  native:
    image: hello-world
    build:
      context: .
      dockerfile: Dockerfile-native
    ports:
      - "127.0.0.1:9003:8080"
