#FROM oracle/graalvm-ce:20.3.0-java11
FROM ghcr.io/graalvm/graalvm-ce:ol7-java11-20.3.0 AS builder
#FROM ghcr.io/graalvm/jdk-community:23 AS builder

RUN gu install native-image

RUN curl --location --output /usr/local/bin/aws-lambda-rie \
        https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod a+x /usr/local/bin/aws-lambda-rie

COPY lambda-bootstrap.sh /
COPY target/uberjar/native-clojure-lambda.jar /

CMD ["/lambda-bootstrap.sh", "/usr/bin/java", \
        "-agentlib:native-image-agent=config-merge-dir=/tmp/native-image,config-write-period-secs=5", \
        "-jar", "native-clojure-lambda.jar"]
