#FROM oracle/graalvm-ce:20.3.0-java11
FROM ghcr.io/graalvm/graalvm-ce:ol7-java11-20.3.0 AS builder
#FROM ghcr.io/graalvm/jdk-community:23 AS builder

RUN gu install native-image

RUN curl --location --output /usr/local/bin/aws-lambda-rie \
        https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie && \
    chmod a+x /usr/local/bin/aws-lambda-rie

COPY target/uberjar/native-clojure-lambda.jar /

RUN native-image \
        --no-fallback \
        --report-unsupported-elements-at-runtime \
        --initialize-at-build-time \
        -H:+PrintAnalysisCallTree \
        -jar native-clojure-lambda.jar native-clojure-lambda && \
    chmod a+x native-clojure-lambda

########################################

FROM ubuntu

COPY --from=builder /usr/local/bin/aws-lambda-rie /usr/local/bin/aws-lambda-rie

COPY lambda-bootstrap.sh /
COPY --from=builder /native-clojure-lambda /

CMD ["/lambda-bootstrap.sh", "/native-clojure-lambda"]
