version: '2.4'
services:

  jvm:
    image: emergency-letter
    build:
      context: .
      dockerfile: Dockerfile-jvm
    ports:
      - "127.0.0.1:9000:8080"

  graalvm:
    image: emergency-letter
    build:
      context: .
      dockerfile: Dockerfile-graalvm
    volumes:
      - ./resources/META-INF/native-image:/tmp/native-image
    ports:
      - "127.0.0.1:9000:8080"

  native:
    image: emergency-letter
    build:
      context: .
      dockerfile: Dockerfile-native
    ports:
      - "127.0.0.1:9000:8080"
