
services:

  jvm:
    image: 'alvartaco/native-clojure-lambda-jvm:0.0.1'
    build:
      context: .
      dockerfile: Dockerfile-jvm
    ports:
      - "127.0.0.1:9001:8080"

  graalvm:
    image: 'alvartaco/native-clojure-lambda-graalvm:0.0.1'
    build:
      context: .
      dockerfile: Dockerfile-graalvm
    volumes:
      - ./target/native-image:/tmp/native-image
    ports:
      - "127.0.0.1:9002:8080"

  native:
    image: 'alvartaco/native-clojure-lambda-native:0.0.1'
    build:
      context: .
      dockerfile: Dockerfile-native
    ports:
      - "127.0.0.1:9003:8080"
