version: '2.4'
services:

  emulator:
    image: emergency-letter-emulator
    build:
      context: .
      dockerfile: Dockerfile-emulator
    volumes:
      - ./resources/META-INF/native-image:/tmp/native-image
    ports:
      - "127.0.0.1:9000:8080"
